### ISSUE TITLE
Broken conversion sf::Color <--> ImVec4

### ISSUE THREAD

**Issue by cgloeckner** [EliasD/imgui-sfml#5]
It seems that ImGui expects a color as `ImVec4` with `r,g,b,a in [0.f, 1.f]`, so the conversion between `sf::Color` and `ImVec4` is broken (I'm sorry, the broken implementation was my suggestion xD). A symptome of that conversion error is, that `sf::Color(255u, 128u, 0u)` is handled as the same as `sf::Color(255u, 255u, 0u)`.

The following conversion for `sf::Color` to `ImVec4` solves this issue:
```c++
#define IM_VEC4_CLASS_EXTRA												\
	ImVec4(sf::Color const const & c)									\
		: ImVec4{c.r / 255.f, c.g / 255.f, c.b / 255.f, c.a / 255.f} {	\
	}																	\
	operator sf::Color() const {										\
		return sf::Color{static_cast<sf::Uint8>(x * 255.f),				\
			static_cast<sf::Uint8>(y * 255.f),							\
			static_cast<sf::Uint8>(z * 255.f),							\
			static_cast<sf::Uint8>(w * 255.f)};							\
	}
```
Corresponding to that, the conversion from `ImVec4` to `sf::Color` should be analogue.

**Comment by EliasD** [comment]
Ha-ha, thanks, fixed :D
